name: 'Install dependencies'
description: 'Build if needed and install the library dependencies'
inputs:
  python-version:
    description: 'The version of Python to install'
    required: true
  username:
    description: 'The pypi username'
    required: true
  compiler-version-password:
    description: 'The password for the compiler-version library'
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.python-version }}" ]; then
          echo "python-version is empty"
          exit 1
        fi

        if [ -z "${{ inputs.username }}" ]; then
          echo "username is empty"
          exit 1
        fi

        if [ -z "${{ inputs.compiler-version-password }}" ]; then
          echo "compiler-version-password is empty"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install build twine packaging

    - name: Clone Amulet-Compiler-Version
      uses: actions/checkout@v4
      with:
        repository: 'Amulet-Team/Amulet-Compiler-Version'
        ref: '3.0'
        path: 'build/pylib/Amulet-Compiler-Version'

    - name: Install Amulet-Compiler-Version
      id: compiler
      uses: ./build/pylib/Amulet-Compiler-Version/.github/actions/install
      with:
        twine-username: ${{ inputs.username }}
        twine-password: ${{ inputs.compiler-version-password }}
